### ISSUE TITLE
CentOS requires the package redhat-lsb

### ISSUE THREAD

**Issue by gammamatrix** [ghoneycutt/puppet-module-nfs#41]
The variable $::lsbmajdistrelease in init.pp will be nil if the package redhat-lsb is not installed.

This will result with the failure message:

"nfs module only supports EL 5 and 6 and lsbmajdistrelease was detected as..."

Here is the package to require:

```
package { 'redhat-lsb':
    ensure  => present,
}
```

The redhat-lsb package is not a part of the minimal install for CentOS 6.
- This probably applies to Scientific Linux as well.

**Comment by rnelson0** [comment]
@ghoneycutt The PR above should fix the issue and bump the version to 1.8.1 so it's ready to go to the forge.

**Comment by ghoneycutt** [comment]
Thanks everyone. This has been fixed.
