### ISSUE TITLE
On RHEL7 $default_nfs_service is undef should be 'nfs-server'?

### ISSUE THREAD

**Issue by FayeG** [ghoneycutt/puppet-module-nfs#49]

**Comment by ghoneycutt** [comment]
Good catch. `nfs::server` should be refactored into the `nfs` class.

**Comment by ghoneycutt** [comment]
Looks like it should just be `nfs`.

https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Storage_Administration_Guide/s1-nfs-start.html

**Comment by fatmcgav** [comment]
On CentOS 7, `nfs` seems to be an alias for `nfs-server`... 

```
[vagrant@nfs01 ~]$ cat /etc/redhat-release
CentOS Linux release 7.1.1503 (Core)
[vagrant@nfs01 ~]$ sudo systemctl status nfs
nfs-server.service - NFS server and services
   Loaded: loaded (/usr/lib/systemd/system/nfs-server.service; enabled)
   Active: active (exited) since Mon 2016-02-08 15:25:03 CVT; 2min 54s ago
 Main PID: 12780 (code=exited, status=0/SUCCESS)

Feb 08 15:25:02 nfs01.lt0772.test systemd[1]: Starting NFS server and services...
Feb 08 15:25:03 nfs01.lt0772.test systemd[1]: Started NFS server and services.
```

So defaulting to `nfs-server` is probably the correct option...

**Comment by pablogosse** [comment]
Seconding fatmcgav. On RHEL7 it should be nfs-server. Can we get this change committed?

Thanks!
Pablo

**Comment by ghoneycutt** [comment]
This is working with the nfs_service set to undef on EL7
