### ISSUE TITLE
Is there an inheritance issue in nfs::server?

### ISSUE THREAD

**Issue by FayeG** [ghoneycutt/puppet-module-nfs#50]
nfs::server inherits class nfs. But class nfs is a parametrized class.

I think puppet docs suggest this should not happen, viz: 
https://docs.puppetlabs.com/puppet/latest/reference/lang_classes.html#inheritance

could this be a grammatical bug for nfs::server to do this?

**Comment by ghoneycutt** [comment]
Good catch. nfs::server should be refactored into the nfs class.
