### ISSUE TITLE
puppet 4 compatibility

### ISSUE THREAD

**Issue by TheMeier** [ghoneycutt/puppet-module-nfs#53]
Warning: Scope(Class[Nfs]): type() DEPRECATED: This function will cease to function on Puppet 4; please use type3x() before upgrading to puppet 4 for backwards-compatibility, or migrate to the new parser's typing system.

**Comment by ghoneycutt** [comment]
Thanks for pointing this out! Do you want to take a crack at converting it to use the is_* functions such as `is_string()`?

**Comment by TheMeier** [comment]
Actually I just stumbled upon this while evaluating modules, as I am using something else now I'm not really into helping out here.
Apart from that, as we are using latest puppet3 and puppetlabs is putting a lot of effort into deprecation warnings my guess is you simply convert all type() calls into type3x() as quick fix and then work on using the new type sytem https://docs.puppetlabs.com/puppet/latest/reference/future_lang_data.html

**Comment by ghoneycutt** [comment]
Support for Puppet v4 and v3 with future parser released in v1.10.0
