### ISSUE TITLE
 Missing package for idmap service on rhel7 in nfs::idmap

### ISSUE THREAD

**Issue by FayeG** [ghoneycutt/puppet-module-nfs#55]
Version 1.9.0 (the latest, of today, that I can upgrade to from puppet forge)

In nfs::idmap, the service requires the file which requires the wrong package on rhel7. The systemd service start file, needed for the service, is provided by package nfs-utils not libnfsidmap.

Either it need changing or both packages need requiring.

**Comment by ghoneycutt** [comment]
I'm building a test environment for EL7 to figure this out.

**Comment by ghoneycutt** [comment]
Could you please test the code from the branch el7? https://github.com/ghoneycutt/puppet-module-nfs/pull/56

I was able to get two systems working where one was an nfs server including the class `nfs::server` and the other was a nfs client including the class `nfs`.

**Comment by jordanconway** [comment]
I have successfully used this branch on RHEL 7 to mount an nfs share.

**Comment by ghoneycutt** [comment]
@jordanconway Thanks!!

Looks like I need to fix the spec tests and this will be ready to merge.
