### ISSUE TITLE
On RHEL 6.3 using facter version 1.6.18 the fact "$operatingsystemmajrelease" is not defined this affects nfs::idmap.pp

### ISSUE THREAD

**Issue by FayeG** [ghoneycutt/puppet-module-nfs#58]
I've had to add this fix to my top level scope get it to work:

snip---
if $operatingsystemmajrelease == undef and !("" in [$operatingsystemmajrelease]) {
  $operatingsystemmajrelease = $::lsbmajdistrelease
}
snip---

See nfs::idmap lines 87-99 of 1.10.0

**Comment by ghoneycutt** [comment]
Hi @FayeG 

I'm glad you were able to find that clever hack to get this going. It will surely help with other modules. Facter 1.6 is quite old. The fact in question was introduced in v1.7 though suggest upgrading to Facter v2.

Best,
-g
