### ISSUE TITLE
Using nfs::idmap on Debian 7, a proposed patch

### ISSUE THREAD

**Issue by FayeG** [ghoneycutt/puppet-module-nfs#61]
Hi,

 I found these patches (against 1.9.0 admittedly but hey) allow me to use idmap on Debian 7. Please could these (or something similar) be folded into the next release?

--- idmap.pp-bak        2015-08-10 14:19:50.506345670 +0100
+++ idmap.pp    2015-08-10 14:29:36.438069675 +0100
@@ -80,6 +80,17 @@
   }

   case $::osfamily {
+    'Debian': {
+      $default_pipefs_directory = 'UNSET'
+      case $::operatingsystemmajrelease {
+        '7': {
+          $default_idmap_service = 'nfs-common'
+          $default_idmap_package = 'nfs-common'
+        }
+      }
+    }
+
+
     'RedHat' : {

       $default_pipefs_directory = 'UNSET'
@@ -128,9 +139,11 @@
   if $pipefs_directory_real != 'UNSET' {
     validate_absolute_path($pipefs_directory_real)
   }
-
-  package { $idmap_package_real:
-    ensure => present,
+
+  if ! defined(Package[$idmap_package_real]){
+    package { $idmap_package_real:
+      ensure => present,
+    }
   }

   file { 'idmapd_conf':

--- init.pp-bak 2015-08-10 14:29:48.270284093 +0100
+++ init.pp     2015-08-10 14:30:30.857055926 +0100
@@ -119,9 +119,12 @@
     $nfs_service_real = $nfs_service
   }

-  package { $nfs_package_real:
-    ensure => present,
+  if ! defined(Package[$nfs_package_real]){
+    package { $nfs_package_real:
+      ensure => present,
+    }
   }
+

   if $nfs_service_real {
     service { 'nfs_service':

**Comment by FayeG** [comment]
Formatting got my diffs. Here's the base64 of same.

LS0tIGlkbWFwLnBwLWJhawkyMDE1LTA4LTEwIDE0OjE5OjUwLjUwNjM0NTY3MCAr
MDEwMAorKysgaWRtYXAucHAJMjAxNS0wOC0xMCAxNDoyOTozNi40MzgwNjk2NzUg
KzAxMDAKQEAgLTgwLDYgKzgwLDE3IEBACiAgIH0KIAogICBjYXNlICQ6Om9zZmFt
aWx5IHsKKyAgICAnRGViaWFuJzogeworICAgICAgJGRlZmF1bHRfcGlwZWZzX2Rp
cmVjdG9yeSA9ICdVTlNFVCcKKyAgICAgIGNhc2UgJDo6b3BlcmF0aW5nc3lzdGVt
bWFqcmVsZWFzZSB7CisgICAgICAgICc3JzogeworICAgICAgICAgICRkZWZhdWx0
X2lkbWFwX3NlcnZpY2UgPSAnbmZzLWNvbW1vbicKKyAgICAgICAgICAkZGVmYXVs
dF9pZG1hcF9wYWNrYWdlID0gJ25mcy1jb21tb24nCisgICAgICAgIH0KKyAgICAg
IH0KKyAgICB9CisKKwogICAgICdSZWRIYXQnIDogewogCiAgICAgICAkZGVmYXVs
dF9waXBlZnNfZGlyZWN0b3J5ID0gJ1VOU0VUJwpAQCAtMTI4LDkgKzEzOSwxMSBA
QAogICBpZiAkcGlwZWZzX2RpcmVjdG9yeV9yZWFsICE9ICdVTlNFVCcgewogICAg
IHZhbGlkYXRlX2Fic29sdXRlX3BhdGgoJHBpcGVmc19kaXJlY3RvcnlfcmVhbCkK
ICAgfQotCi0gIHBhY2thZ2UgeyAkaWRtYXBfcGFja2FnZV9yZWFsOgotICAgIGVu
c3VyZSA9PiBwcmVzZW50LAorICAKKyAgaWYgISBkZWZpbmVkKFBhY2thZ2VbJGlk
bWFwX3BhY2thZ2VfcmVhbF0peworICAgIHBhY2thZ2UgeyAkaWRtYXBfcGFja2Fn
ZV9yZWFsOgorICAgICAgZW5zdXJlID0+IHByZXNlbnQsCisgICAgfQogICB9CiAK
ICAgZmlsZSB7ICdpZG1hcGRfY29uZic6Cg==

LS0tIGluaXQucHAtYmFrCTIwMTUtMDgtMTAgMTQ6Mjk6NDguMjcwMjg0MDkzICsw
MTAwCisrKyBpbml0LnBwCTIwMTUtMDgtMTAgMTQ6MzA6MzAuODU3MDU1OTI2ICsw
MTAwCkBAIC0xMTksOSArMTE5LDEyIEBACiAgICAgJG5mc19zZXJ2aWNlX3JlYWwg
PSAkbmZzX3NlcnZpY2UKICAgfQogCi0gIHBhY2thZ2UgeyAkbmZzX3BhY2thZ2Vf
cmVhbDoKLSAgICBlbnN1cmUgPT4gcHJlc2VudCwKKyAgaWYgISBkZWZpbmVkKFBh
Y2thZ2VbJG5mc19wYWNrYWdlX3JlYWxdKXsKKyAgICBwYWNrYWdlIHsgJG5mc19w
YWNrYWdlX3JlYWw6CisgICAgICBlbnN1cmUgPT4gcHJlc2VudCwKKyAgICB9CiAg
IH0KKyAgCiAKICAgaWYgJG5mc19zZXJ2aWNlX3JlYWwgewogICAgIHNlcnZpY2Ug
eyAnbmZzX3NlcnZpY2UnOgo=

**Comment by ghoneycutt** [comment]
Hi @FayeG 

Could you please submit a pull request of your changes? That way I can see the diff and optionally press the merge button to get your code merged.

Here is a guide from GitHub

https://guides.github.com/activities/contributing-to-open-source/

Here is a learning resource I help maintain with the actual commands.

https://github.com/unixmonkey/learngit
