### ISSUE TITLE
nfs_service missing dependencies under Solaris/OmniOS

### ISSUE THREAD

**Issue by westbywest** [ghoneycutt/puppet-module-nfs#63]
While running a catalog with this module included on an OmniOS v5.11 machine, observed the following error:

```
Error: Could not start Service[nfs_service]: Execution of '/usr/sbin/svcadm enable -s nfs/client' returned 4: svcadm: Instance "svc:/network/nfs/client:default" has unsatisfied dependencies.
Error: /Stage[main]/Nfs/Service[nfs_service]/ensure: change from stopped to running failed: Could not start Service[nfs_service]: Execution of '/usr/sbin/svcadm enable -s nfs/client' returned 4: svcadm: Instance "svc:/network/nfs/client:default" has unsatisfied dependencies.
```

No parameters or mounts were given to the nfs module yet, it was just included via hiera.

Running these commands at a root prompt and repeating puppet agent run saw no error.

```
svcadm -v enable network/nfs/nlockmgr
svcadm -v enable network/nfs/status
svcadm -v enable network/nfs/client
```

The puppet master was a CentOS machine running puppetserver-2.2.1-1.el7.noarch, and the local puppet agent on the OmniOS machine was  v4.3.1.

**Comment by ghoneycutt** [comment]
Hi @westbywest 

I'm not familiar with Omni, though pleased to add support for it. Could you please run `facter` and put the output in a gist for me?

**Comment by westbywest** [comment]
This is OmniOS v5.11, which is derived from Solaris v11, which I'm presently testing out under vagrant.  This had the OpenCSW tools installed, and puppet agent v4.3.1 installed via gem.

Googling on the "has unsatisfied dependencies" error message suggests this problem may also occur on Solaris.

Here is the gist, with SSH keys and UUID XXX-ed out: https://gist.github.com/westbywest/da0ae622f68324d20b80

Getting OmniOS running under vagrant took some effort in building a custom box, since the pre-built boxes from http://omnios.omniti.com/ appeared to be missing some necessary pieces.  (I can share another gist about getting OmniOS to run under vagrant, if desired.)

**Comment by ghoneycutt** [comment]
Thanks for the info, these really help when porting to a different os.

Are you including `nfs` or `nfs::server` ?

For the nfs class, the code only manages 'nfs/client' service. Perhaps we also have to manage nfs/status and nfs/nlockmgr ?

**Comment by westbywest** [comment]
I was only including the nfs class, not nfs::server.  Yes, my guess is that the client service does depend on status and nlockmgr.  That is, I get the error above unless I've enabled nfs/status and nfs/nlockmgr prior.

**Comment by ghoneycutt** [comment]
Check you try running the code from PR #66 and let me know how it goes?

**Comment by ghoneycutt** [comment]
I was not able to duplicate using Vagrant. Please re-open if this is still an issue. Thank you!
