### ISSUE TITLE
mount directories

### ISSUE THREAD

**Issue by joao-matos** [ghoneycutt/puppet-module-nfs#75]
what about the directories? one can't have a mount without a directory

**Comment by ghoneycutt** [comment]
It creates the directory for you.

it uses types::mount

https://github.com/ghoneycutt/puppet-module-nfs/blob/master/manifests/init.pp#L145

which creates the directory

https://github.com/ghoneycutt/puppet-module-types/blob/master/manifests/mount.pp#L25
