### ISSUE TITLE
idmapd service should not be running on RedHat 7

### ISSUE THREAD

**Issue by edestecd** [ghoneycutt/puppet-module-nfs#77]
https://access.redhat.com/solutions/209553

We should not manage the service or ensure stopped here on RedHat >= 7
https://github.com/ghoneycutt/puppet-module-nfs/blob/master/manifests/idmap.pp#L149

**Comment by ghoneycutt** [comment]
Note: This applies to being a client, not a server. idmapd.conf is used though for server and client.

**Comment by edestecd** [comment]
OK, so we maybe we just need an option to turn off service management?

**Comment by ghoneycutt** [comment]
Yep. Just making notes. I'm working on adding a Vagrant setup to functionally test the different platforms.

**Comment by ghoneycutt** [comment]
This will be solved by V2 in PR #78
